# Generated by Django 3.0.3 on 2020-07-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PGLapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentdb',
            table='comment',
        ),
    ]
